export const SET_GET_START_POINT = 'SET_GET_START_POINT';
export const SET_SORT_POINTS = 'SET_SORT_POINTS';
export const SET_ADD_NEXT_POINT = 'SET_ADD_NEXT_POINT';
export const SET_FIX_RIGHT_TURN = 'SET_FIX_RIGHT_TURN';
export const SET_DONE = 'SET_DONE';
